name: "astrafy_takehome"
version: "1.0.0"
config-version: 2

profile: "BigQuery"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics_project:
    staging:
      +schema: dbt_phowson

    marts:
      +schema: marts