name: "astrafy_takehome"
version: "1.3.0"
config-version: 1

profile: "BigQuery"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  astrafy_takehome:
    +schema: analytics
    
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
